### ISSUE TITLE
What data source are used for these analyses?

### ISSUE THREAD

**Issue by firaswehbe** [all-of-us/analytics#1]
I am with the IPMC HPO. The only source data we have access to are the workqueue export from HealthPro. That doesn't seem to work here (export to the right `../../data` path and renamed the file etc..)

**Comment by eweitz** [comment]
The data comes from a few timestamp columns in the RDR.  Providing wider access to synthetic data for this is on our roadmap, but data for these analyses is not currently available outside the Operations and Analytics team.  

We are now allowed to send out row-level data, and are working on a version that has dates.  We don't have permission to share that yet, but hopefully will in the coming weeks.

If you'd like to know when either of these datasets become available, please email scottsu@broadinstitute.org.
